hello/urls.py
__author__ = 'Administrator'

from django.conf.urls import url


from . import views

app_name = 'hello'
urlpatterns = [
    #ex: /polls/
    #url(r'^$', views.index, name='index'),
    #ex: /polls/5/
    #url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    #ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #ex: /polls/5/vote/
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    #ex: /polls/5/hello
    #url(r'^(?P<parram>[0-9]+)/hello/$', views.hello, name='hello'),

    #Generic View
    url(r'^$', views.hello, name='hello'),
    url(r'^crudops$', views.crudops, name='crudops'),
    url(r'^datamanipulation$', views.datamanipulation, name='datamanipulation'),
    url(r'^article/(?P<articleId>[0-9]+)/$', views.viewArticle),
    url(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.viewArticles, name='articles'),
    url(r'^connection/',views.TemplateView.as_view(), name='template_view'),
    url(r'^login/', views.login, name = 'login'),
    url(r'^search-form/', views.TemplateView1.as_view(), name='search_form'),
    url(r'^search/$', views.search, name='search'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='django.contrib.auth.views.login'),

]

training/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^reporting/', include('reporting.urls')),
    url(r'^hello/', include('hello.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

hello/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Dreamreal(models.Model):
    website = models.CharField(max_length=50)
    mail = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    phonenumber = models.IntegerField()
    online = models.ForeignKey('Online', default=1)

    class Meta:
        db_table="dreamreal"

class Online(models.Model):
    domain = models.CharField(max_length=30)

    class Meta:
        db_table = 'online'

hello/forms.py
__author__ = 'Administrator'
from django import forms

class LoginForm(forms.Form):
    user = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)

class CommemtForm(forms.Form):
    name = forms.CharField()
    url = forms.URLField()
    comment = forms.CharField(widget=forms.Textarea)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=20)
    email   = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

hello/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.http import HttpResponse
from django.core.mail import send_mail
from django.http import HttpResponseRedirect


from hello.models import Dreamreal
from hello.forms import LoginForm, ContactForm
from querybuilder.query import Query

import datetime

def hello(request):
   today = datetime.datetime.now().date()
   daysOfWeek = ['Mon', 'Tue', 'Web', 'Thu', 'Fri', 'Sat', 'Sun']
   return render(request, "hello/index.html", {"today" : today, "days_of_week": daysOfWeek})

def crudops(request):
   dreamreal = Dreamreal(
      website  = "www.chaulaode.com",
      mail     = "chaulaode@ved.com.vn",
      name     = "chau",
      phonenumber = "0975458035"
   )
   dreamreal.save()

   #Read all entries
   objects = Dreamreal.objects.all()
   res = 'Printing all Dreamreal entries in the DB: <br>'

   for elt in objects:
      res += elt.name+"<br>"

   #Read a specific entry:
   chau = Dreamreal.objects.get(name="chau")
   res += "Printing One entry <br>"
   res += chau.name

   #delete a specific entry:
   res += '<br> Deleting an entry <br>'
   chau.delete()

   #update
   dreamreal = Dreamreal(
      website  = "ww.apolo.com",
      mail     = "apolo@ved.com.vn",
      name     = "apolo",
      phonenumber = "01234783472"
   )
   dreamreal.save()
   res += 'Updating entry<br>'

   dreamreal = Dreamreal.objects.get(name = 'apolo')
   dreamreal.name = 'chaulaode'
   dreamreal.save()

   return HttpResponse(res)

def datamanipulation(request):
   res = ''

   #Filtering data:
   qs = Dreamreal.objects.filter(name='paul')
   res += "Found : %s results<br>"%len(qs)

   #Ordering results
   qs = Dreamreal.objects.order_by("name")

   for elt in qs:
      res += elt.name + '<br>'

   return HttpResponse(res)

def viewArticle(request, articleId):
   text = "displaying article Number: %s" %articleId
   #return HttpResponse(text)
   return redirect(viewArticles, year='2045', month='02')

def viewArticles(request, year, month):
   text = "Displaying article of: %s/%s"%(year, month)
   return HttpResponse(text)

def login(request):
   username = "not logged in"

   if request.method == "POST":

      #Get the posted form
      MyLoginForm = LoginForm(request.POST)
      if MyLoginForm.is_valid():
         username = MyLoginForm.cleaned_data['username']
   else:
      MyLoginForm = LoginForm()

   return render(request, 'hello/loggedin.html',{"username": username})

class TemplateView(generic.TemplateView):
    template_name = 'hello/login.html'

class TemplateView1(generic.TemplateView):
    template_name = 'hello/search_form.html'

def search_form(request):
   render(request, 'hello/search_form.html')

def search(request):
   errors = []
   if 'q' in request.GET:
      q = request.GET['q']
      if not q:
         errors.append('Enter a search term.')
      elif len(q)> 20:
          errors.append('Please enter at most 20 characters.')
      else:
          query = Query().from_table('dreamreal')
          query.where(name__contains=q).where(website__contains='any1')
          dreamreals = query.get_sql()
          return HttpResponse(dreamreals)
          #dreamreals = Dreamreal.objects.filter(name__contains=q)
          return render(request, 'hello/search_results.html', {'dreamreals': dreamreals, 'query': q})
   else:
      message = 'You submitted an empty form.'

   return render(request, 'hello/search_form.html', {'errors': errors})

# def contact(request):
#     errors = []
#     if request.method == 'POST':
#         if not request.POST.get('subject', ''):
#             errors.append('Enter a subject.')
#         if not request.POST.get('message', ''):
#             errors.append('Enter a message.')
#         if not request.POST.get('email', '') and '@' not in request.POST['email']:
#             errors.append('Enter a valid e-mail address.')
#         if not errors:
#             send_mail(
#                 request.POST['subject'],
#                 request.POST['message'],
#                 request.POST.get('email', 'noreply@example.com'),
#                 ['siteowner@example.com'],
#             )
#             return HttpResponseRedirect('/contact/thanks/')
#     return render(request, 'hello/contact_form.html',
#         {
#             'errors': errors,
#             'subject': request.POST.get('subject', ''),
#             'message': request.POST.get('message', ''),
#             'email': request.POST.get('email', ''),
#         })

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['site@example.com'],
            )
            return HttpResponse('Thank you!')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'hello/contact_form.html', {'form': form})

hello/templates/hello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css" />
    <title>{% block title %}My amazing site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">Blog</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

hello/templates/hello/base_news.html
{% extends "base.html" %}
{% load poll_extras %}
{% block title %}My amazing blog{% endblock %}

{% block content %}
    <h1>Xin chao</h1>
    <p>Chau Lao De</p>
{% endblock %}

hello/templates/hello/base_sports.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}

{% block content %}
{% for entry in blog_entries %}
    <h2>{{ entry.title }}</h2>
    <p>{{ entry.body }}</p>
{% endfor %}
{% endblock %}

hello/templates/hello/contact_form.html
<html>
<head>
    <title>Contact us</title>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
</head>
<body>

    <h1>Contact us</h1>

    {% if form.errors %}
       <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
       </p>
    {% endif %}

    <form action="{% url 'hello:contact' %} " method="post">
        {% csrf_token %}
       <div class="field ">
           {{ form.subject.errors }}
           <label for="id_subject"> Subject:</label>
           {{ form.subject }}
       </div>
        <div class="field">
           {{ form.email.errors }}
           <label for="id_email"> Email:</label>
           {{ form.email }}
       </div>
        <div class="field{% if form.message.errors %} errors

       {% endif %}">
           <label for="id_message"> Message:</label>
           {{ form.message }}
       </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

hello/templates/hello/index.html
{% extends "hello\main_template.html" %}
{% block title %}My Hello Page{% endblock %}
{% block content %}
Hello World!!!<p>Today is {{today}}</p>

We are
{% if today.day == 1 %}

the first day of month.
{% elif today.day == 31 %}

the last day of month.
{% else %}

I don't know.
{%endif%}

<p>
  {% for day in days_of_week %}
  {{ day }}
</p>
{% endfor %}
{% endblock %}

hello/templates/hello/loggedin.html
<html>

   <body>
      You are : <strong>{{username}}</strong>
   </body>

</html>

hello/templates/hello/login.html
<html>
   <body>

      <form action="{% url 'hello:login' %}" method="post">
         {% csrf_token %}
         
         <div style = "max-width:470px;">
            <center>
                <label>Username</label>
               <input type = "text" style = "margin-left:20%;" 
                  placeholder = "Identifiant" name = "username" />
            </center>
         </div>
			
         <br>
         
         <div style = "max-width:470px;">
            <center>
                <label>Password</label>
               <input type = "password" style = "margin-left:20%;" 
                  placeholder = "password" name = "password" />
            </center>
         </div>
			
         <br>
         
         <div style = "max-width:470px;">
            <center> 
            
               <button style = "border:0px; background-color:#4285F4; margin-top:8%;
                  height:35px; width:80%;margin-left:19%;" type = "submit" 
                  value = "Login" >
                  <strong>Login</strong>
               </button>
               
            </center>
         </div>
         
      </form>
      
   </body>
</html>

hello/templates/hello/main_template.html
<html>
   <head>
      
      <title>
         {% block title %}Page Title{% endblock %}
      </title>
      
   </head>
	
   <body>
   
      {% block content %}
         Body content
      {% endblock %}
      
   </body>
</html>

hello/templates/hello/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
                <li style="color: red;">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'hello:search' %}" method="get">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

hello/templates/hello/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if dreamreals %}
    <p>Found {{ dreamreals|length }} dreamreal{{ dreamreals|pluralize }}.</p>
    <ul>
        {% for dreamreal in dreamreals %}
        <li>{{ dreamreal.name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No dreamreals matched your search criteria.</p>
{% endif %}