hello/urls.py
__author__ = 'Administrator'

from django.conf.urls import url


from . import views

app_name = 'hello'
urlpatterns = [
    #ex: /polls/
    #url(r'^$', views.index, name='index'),
    #ex: /polls/5/
    #url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    #ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    #ex: /polls/5/vote/
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    #ex: /polls/5/hello
    #url(r'^(?P<parram>[0-9]+)/hello/$', views.hello, name='hello'),

    #Generic View
    url(r'^$', views.hello, name='hello'),
    url(r'^crudops$', views.crudops, name='crudops'),
    url(r'^datamanipulation$', views.datamanipulation, name='datamanipulation'),
    url(r'^article/(?P<articleId>[0-9]+)/$', views.viewArticle),
    url(r'^articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', views.viewArticles, name='articles'),
    url(r'^connection/',views.TemplateView.as_view(), name='template_view'),
    url(r'^login/', views.login, name = 'login'),
    url(r'^search-form/', views.TemplateView1.as_view(), name='search_form'),
    url(r'^search/$', views.search, name='search'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='django.contrib.auth.views.login'),

]

reporting/urls.py
__author__ = 'Administrator'
from django.conf.urls import url
from . import views
app_name = 'reporting'
urlpatterns = [
     url(r'^excel-report$', views.excel_export, name='excel_export'),
    url(r'^$', views.index, name='index'),
    url(r'^tables$', views.tables, name='tables'),
    url(r'^table-dynamic$', views.table_dynamic, name='table_dynamic'),
]

training/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^reporting/', include('reporting.urls')),
    url(r'^hello/', include('hello.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

reporting/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AirpayDaily(models.Model):
    type = models.IntegerField()
    date = models.DateField()
    location = models.CharField(max_length=2)
    extra = models.CharField(max_length=128)
    data = models.TextField()

    class Meta:
        managed = False
        db_table = 'airpay_daily'
        unique_together = (('type', 'date', 'location', 'extra'),)


class AirpayRealtime(models.Model):
    type = models.IntegerField()
    date = models.DateField()
    tick = models.IntegerField()
    location = models.CharField(max_length=2)
    data = models.TextField()

    class Meta:
        managed = False
        db_table = 'airpay_realtime'
        unique_together = (('type', 'date', 'tick', 'location'),)


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class BankAccountTab(models.Model):
    id = models.BigIntegerField(primary_key=True)
    uid = models.BigIntegerField()
    channel_id = models.IntegerField()
    account_no = models.CharField(max_length=64)
    type = models.IntegerField()
    flag = models.IntegerField()
    create_time = models.IntegerField()
    bind_time = models.IntegerField()
    update_time = models.IntegerField()
    mobile_no = models.CharField(max_length=16)
    ic_no = models.CharField(max_length=32)
    ic_verified = models.IntegerField()
    token = models.CharField(max_length=128)
    extra_data = models.TextField()

    class Meta:
        managed = False
        db_table = 'bank_account_tab'


class ChannelTab(models.Model):
    channel_id = models.IntegerField(primary_key=True)
    country = models.CharField(max_length=2)
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=256)
    type = models.IntegerField()
    flag = models.IntegerField()
    gateway = models.IntegerField()
    currency = models.CharField(max_length=3)
    discount = models.FloatField()
    icon = models.CharField(max_length=2048)
    priority = models.IntegerField()
    availability = models.IntegerField()
    extra_data = models.CharField(max_length=4096)
    txn_min = models.BigIntegerField()
    txn_max = models.BigIntegerField()
    min_version_ios = models.IntegerField()
    min_version_android = models.IntegerField()
    message = models.CharField(max_length=1024)

    class Meta:
        managed = False
        db_table = 'channel_tab'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Dreamreal(models.Model):
    website = models.CharField(max_length=50)
    mail = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    phonenumber = models.IntegerField()
    online_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'dreamreal'


class Online(models.Model):
    domain = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'online'


class OrderTab(models.Model):
    order_id = models.BigIntegerField(primary_key=True)
    uid = models.BigIntegerField()
    type = models.IntegerField()
    status = models.IntegerField()
    currency = models.CharField(max_length=3)
    currency_amount = models.BigIntegerField()
    create_time = models.IntegerField()
    expired_time = models.IntegerField()
    valid_time = models.IntegerField()
    update_time = models.IntegerField()
    topup_channel_id = models.IntegerField()
    topup_channel_txn_id = models.CharField(max_length=64)
    topup_account_id = models.CharField(max_length=64)
    payment_channel_id = models.IntegerField()
    payment_channel_txn_id = models.CharField(max_length=64)
    payment_account_id = models.CharField(max_length=64)
    item_id = models.CharField(max_length=16)
    item_amount = models.IntegerField()
    item_name = models.CharField(max_length=64)
    item_image = models.CharField(max_length=256)
    ip = models.IntegerField()
    action_country = models.CharField(max_length=2)
    memo = models.CharField(max_length=16)
    topup_txn_id = models.BigIntegerField()
    payment_txn_id = models.BigIntegerField()
    extra_data = models.TextField()
    event_id = models.BigIntegerField()
    topup_payable_amount = models.BigIntegerField()
    payment_payable_amount = models.BigIntegerField()
    topup_cash_amount = models.BigIntegerField()
    payment_cash_amount = models.BigIntegerField()

    class Meta:
        managed = False
        db_table = 'order_tab'


class PollsAlbum(models.Model):
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    num_stars = models.IntegerField()
    artist = models.ForeignKey('PollsMusician', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'polls_album'


class PollsChoice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField()
    question = models.ForeignKey('PollsQuestion', models.DO_NOTHING)
    created = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'polls_choice'


class PollsFruit(models.Model):
    name = models.CharField(primary_key=True, max_length=100)

    class Meta:
        managed = False
        db_table = 'polls_fruit'


class PollsGroup(models.Model):
    name = models.CharField(max_length=128)

    class Meta:
        managed = False
        db_table = 'polls_group'


class PollsMembership(models.Model):
    date_joined = models.DateField()
    invite_reason = models.CharField(max_length=64)
    group = models.ForeignKey(PollsGroup, models.DO_NOTHING)
    person = models.ForeignKey('PollsPerson', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'polls_membership'


class PollsMusician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'polls_musician'


class PollsPerson(models.Model):
    name = models.CharField(max_length=60)
    shirt_size = models.CharField(max_length=1)

    class Meta:
        managed = False
        db_table = 'polls_person'


class PollsQuestion(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    class Meta:
        managed = False

reporting/forms.py
from django import forms

class DateToDateForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control has-feedback-left datepicker', 'placeholder': 'Start date', 'aria-describedby': 'inputSuccess2Status'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control has-feedback-left datepicker', 'placeholder': 'End date', 'aria-describedby': 'inputSuccess2Status'}))
    orderId = forms.CharField(max_length=64, required=False, widget=forms.TextInput(attrs={'class':'form-control has-feedback-left', 'placeholder': 'Order ID', 'aria-describedby': 'inputSuccess2Status'}))
    uid = forms.CharField(max_length=64, required=False, widget=forms.TextInput(attrs={'class':'form-control has-feedback-left', 'placeholder': 'UID', 'aria-describedby': 'inputSuccess2Status'}))

reporting/views.py
import urllib

__author__ = 'Administrator'

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.db.models import Q, F


from models import OrderTab
from sortheader import SortHeaders
from forms import DateToDateForm
from datetime import datetime,timedelta
from excel_utils import WriteToExcel

import time
import constants


LIST_HEADERS = (
    ('OrderId', 'order_id'),
    ('UID', 'uid'),
    ('Create time', 'create_time'),
    ('Update time', 'update_time'),
)

DEFAULT_ORDER = (0)
DEFAULT_ORDER_TYPE = 'desc'

def index(request):
    return render(request, 'reporting/base_index.html', {'hello': 'xin chao chaulaode'})

def tables(request):
    return render(request, 'reporting/base_tables.html', {'variable': 'chaulaode'})

@login_required(redirect_field_name='/reporting/table_dynamic/',login_url='/admin/')
@permission_required('reporting', raise_exception=True)
def table_dynamic(request):

    form = DateToDateForm(request.GET)
    start_date = request.GET.get('start_date', '')
    end_date = request.GET.get('end_date', '')

    if not start_date:
        DAY = timedelta(constants.START_DATE)
        start_date = datetime.today() - DAY

    else:
         start_date = datetime.strptime(start_date, '%Y-%m-%d')- timedelta(days=1)
    if not end_date:
        end_date = datetime.now().date()
        form = DateToDateForm(initial={'start_date':start_date, 'end_date':end_date})
    else:
        end_date = datetime.strptime(end_date, '%Y-%m-%d') + timedelta(days=1)

    uid = request.GET.get('uid', '')
    orderId = request.GET.get('orderId', '')


    start_date = int(time.mktime(start_date.timetuple()))
    end_date = int(time.mktime(end_date.timetuple()))

    sort_headers = SortHeaders(request, LIST_HEADERS, DEFAULT_ORDER, DEFAULT_ORDER_TYPE)
    objects = OrderTab.objects.filter(
        create_time__gt = start_date,
        create_time__lt = end_date,
        order_id__contains=orderId,
        uid__contains=uid
    ).order_by(sort_headers.get_order_by())

    if 'excel' in request.GET:
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
        xlsx_data = WriteToExcel(objects)
        response.write(xlsx_data)
        return response

    paginator = Paginator(objects, constants.NUM_PER_PAGE)
    page = request.GET.get('page')

    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        objects = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        objects = paginator.page(paginator.num_pages)

    return render(
        request,
        'reporting/base_table_dynamic.html',
        {'order_list': objects, 'headers': list(sort_headers.headers()),'url':request.get_full_path(), 'form': form}
    )

def excel_export(request):
    import xlsxwriter
    import StringIO
    output = StringIO.StringIO()
    workbook = xlsxwriter.Workbook(output)
    worksheet = workbook.add_worksheet()
    expenses = (
        ['Rent', 1000],
        ['Gas', 100],
        ['Food', 300],
        ['Gym', 50]
    )
    row = 0
    col = 0

    for item, cost in (expenses):
        worksheet.write(row, col, item)
        worksheet.write(row, col+1, cost)
        row+=1

    workbook.close()

    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename=Report.xlsx'
    response.write('Report.xlsx')
    return response

reporting/templates/reporting/__filter.html
<div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
      <div class="row">
          <div class="col-xs-6">
               <div class = "input-group input-group-sm">
                 <span class = "input-group-addon">From</span>
                  {{ form.start_date }}
              </div>
              <div class = "input-group input-group-sm">
                  <span class = "input-group-addon">To</span>
                {{ form.end_date }}
              </div>
          </div>
      </div>

       <div class="row">
          <div class="col-xs-6">
               <div class = "input-group input-group-sm">
                 <span class = "input-group-addon">Order ID</span>
                   {{ form.orderId }}

              </div>
              <div class = "input-group input-group-sm">
                  <span class = "input-group-addon">UID</span>
                 {{ form.uid }}
              </div>
          </div>
      </div>
       <div class="row">
          <div class="form-group col-md-9">
            <div class="col-md-10">
              <button type="submit" class="btn btn-primary">Cancel</button>
              <button type="submit" class="btn btn-success">Submit</button>
            </div>


          </div>
           <div class="col-md-3">
                  <input type="submit" name="excel" value="Excel Export" class="btn btn-success"/>
            </div>
       </div>
       <div class="ln_solid"></div>
       <div class="row">
          <div class="col-sm-6" id="datatable_wrapper">
              <div class="dataTables_length" id="datatable_length">
                  <label>Show</label>
                      <select name="datatable_length" aria-controls="datatable" class="form-control input-sm">
                          <option value="10">10</option><option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                      </select>
                  <label>
                      entries</label>
              </div>
              </div>
      </div>
 </div>

reporting/templates/reporting/__footer.html
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>

reporting/templates/reporting/__sidebar-footer.html
<div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>

reporting/templates/reporting/__sidebar.html
{% block sidebar %}
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="index.html">Dashboard</a></li>
          <li><a href="index2.html">Dashboard2</a></li>
          <li><a href="index3.html">Dashboard3</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="form.html">General Form</a></li>
          <li><a href="form_advanced.html">Advanced Components</a></li>
          <li><a href="form_validation.html">Form Validation</a></li>
          <li><a href="form_wizards.html">Form Wizard</a></li>
          <li><a href="form_upload.html">Form Upload</a></li>
          <li><a href="form_buttons.html">Form Buttons</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="general_elements.html">General Elements</a></li>
          <li><a href="media_gallery.html">Media Gallery</a></li>
          <li><a href="typography.html">Typography</a></li>
          <li><a href="icons.html">Icons</a></li>
          <li><a href="glyphicons.html">Glyphicons</a></li>
          <li><a href="widgets.html">Widgets</a></li>
          <li><a href="invoice.html">Invoice</a></li>
          <li><a href="inbox.html">Inbox</a></li>
          <li><a href="calendar.html">Calendar</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="{% url 'reporting:tables' %}">Tables</a></li>
          <li><a href="{% url 'reporting:table_dynamic' %}">Table Dynamic</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="chartjs.html">Chart JS</a></li>
          <li><a href="chartjs2.html">Chart JS2</a></li>
          <li><a href="morisjs.html">Moris JS</a></li>
          <li><a href="echarts.html">ECharts</a></li>
          <li><a href="other_charts.html">Other Charts</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
          <li><a href="fixed_footer.html">Fixed Footer</a></li>
        </ul>
      </li>
    </ul>
  </div>
  <div class="menu_section">
    <h3>Live On</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="e_commerce.html">E-commerce</a></li>
          <li><a href="projects.html">Projects</a></li>
          <li><a href="project_detail.html">Project Detail</a></li>
          <li><a href="contacts.html">Contacts</a></li>
          <li><a href="profile.html">Profile</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="page_403.html">403 Error</a></li>
          <li><a href="page_404.html">404 Error</a></li>
          <li><a href="page_500.html">500 Error</a></li>
          <li><a href="plain_page.html">Plain Page</a></li>
          <li><a href="login.html">Login Page</a></li>
          <li><a href="pricing_tables.html">Pricing Tables</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
            <li><a href="#level1_1">Level One</a>
            <li><a>Level One<span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu">
                <li class="sub_menu"><a href="level2.html">Level Two</a>
                </li>
                <li><a href="#level2_1">Level Two</a>
                </li>
                <li><a href="#level2_2">Level Two</a>
                </li>
              </ul>
            </li>
            <li><a href="#level1_2">Level One</a>
            </li>
        </ul>
      </li>
      <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
    </ul>
  </div>

</div>
{% endblock %}

reporting/templates/reporting/base_table_dynamic.html
{% extends "reporting/__base.html" %}
{% load static %}
{% load header_tag %}
{% load pagination_tag %}
{% load timetags %}
{% block title %}My amazing website | table dynamic{% endblock %}

{% block stylesheet %}
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'reporting/vendors/bootstrap/dist/css/bootstrap.min.css' %}"/>
    <!-- Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'reporting/vendors/font-awesome/css/font-awesome.min.css' %}"/>
    <!-- iCheck -->
    <link rel="stylesheet" type="text/css" href="{% static 'reporting/vendors/iCheck/skins/flat/green.css' %}"/>
    <!-- Custom Theme Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'reporting/build/css/custom.min.css' %}"/>
{% endblock %}

{% block content %}
    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Users <small>Some examples to get you started</small></h3>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_content">
                   <form action="{% url 'reporting:table_dynamic' %} " method="get">
                    {% csrf_token %}
                   <!-- Start filter /-->
                    {% include "reporting/__filter.html" %}
                  <!-- End filter /-->
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                            {% table_header headers url%}
                        </tr>
                      </thead>


                      <tbody>
                       {% for order in order_list %}<tr class="{% cycle odd,even %}">
                            <td><a href="{{ order.get_absolute_url|escape }}">{{ order.order_id|escape }}</a></td>
                            <td>{{ order.uid|escape }}</td>
                            <td>{{ order.create_time|print_timestamp|date|escape }}</td>
                            <td>{{ order.update_time|print_timestamp|date|escape }}</td>
                          </tr>
                      {% endfor %}
                       </tbody>

                    </table>

                  <!-- Start pagging /-->

                    {% table_pagination order_list url %}

                  <!-- End pagging /-->
                  </form>
                  </div>

                </div>

              </div>

                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}
    <!-- jQuery -->
    <script src="{% static 'reporting/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'reporting/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'reporting/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'reporting/vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
   <script src="{% static 'reporting/vendors/iCheck/icheck.min.js' %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static 'reporting/build/js/custom.min.js' %}"></script>


    <!-- jQuery -->
    <script src="{% static 'reporting/vendors/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'reporting/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'reporting/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
     <script src="{% static 'reporting/vendors/nprogress/nprogress.js' %}"></script>



    <!-- bootstrap-daterangepicker -->
    <script src="{% static 'reporting/js/moment/moment.min.js' %}"></script>
    <script src="{% static 'reporting/js/datepicker/daterangepicker.js' %}"></script>

    <script>
      $(document).ready(function() {
        $('.datepicker').daterangepicker({
          singleDatePicker: true,
          calender_style: "picker_1",
          format: 'YYYY-MM-DD'
        }, function(start, end, label) {
          console.log(start.toISOString(), end.toISOString(), label);
        });

      });
    </script>
    <!-- /bootstrap-daterangepicker -->

{% endblock %}

reporting/templates/reporting/table_header.html
{% for header in headers %}<th{{ header.class_attr }}>
  {% if header.sortable %}<a href="{{ header.url|escape }}&{{ url_query }}">{% endif %}
  {{ header.text }}
  {% if header.sortable %}</a>{% endif %}
</th>{% endfor %}